# Generated by Django 5.0.3 on 2024-06-16 16:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('titre', models.CharField(max_length=500)),
                ('Auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PosaxApp.post')),
                ('Photo', models.ImageField(upload_to='PhotosArticle')),
                ('intro', models.TextField(blank=True, null=True)),
                ('paragraphe1', models.TextField()),
                ('paragraphe2', models.TextField(blank=True, null=True)),
            ],
            bases=('PosaxApp.post',),
        ),
        migrations.CreateModel(
            name='Oeuvre',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PosaxApp.post')),
                ('categorie', models.CharField(max_length=800)),
                ('Photo1', models.ImageField(upload_to='PhotosOeuvre')),
                ('Photo2', models.ImageField(blank=True, null=True, upload_to='PhotoOeuvre')),
                ('Photo3', models.ImageField(blank=True, null=True, upload_to='PhotoOeuvre')),
                ('Photo4', models.ImageField(blank=True, null=True, upload_to='PhotoOeuvre')),
            ],
            bases=('PosaxApp.post',),
        ),
    ]
